version: '3.9'
services:
  db:
    image: postgres:latest
    container_name: user-service
    restart: unless-stopped
    tty: true
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
      - PGDATA=/var/lib/postgresql/data/user-service
    ports:
      - '25432:5432'
    volumes:
      - user-service:/var/lib/postgresql/data
volumes:
  user-service:
